### ISSUE TITLE
"Shaky" camera when AI takes its turn

### ISSUE THREAD

**Issue by rm-code** [Zireael07/veins-of-the-earth-love#6]
![camera](https://cloud.githubusercontent.com/assets/11627131/18890969/b2fe1852-8503-11e6-80de-3c0da755efad.gif)

You can see the camera jumps a few pixels back and forth while the AI is moving.

**Comment by Zireael07** [comment]
Ought to be closed for good with 222a347603826e1307f8751b2396995e308c2509
